"""sales_invoicing_payments

Revision ID: 7381f75d770f
Revises: a1574aea20b7
Create Date: 2026-09-18 14:36:05.121362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7381f75d770f'
down_revision: Union[str, Sequence[str], None] = 'a1574aea20b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_cliente_id'), 'ventas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_index(op.f('ix_ventas_usuario_id'), 'ventas', ['usuario_id'], unique=False)
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('(producto_id IS NOT NULL AND servicio_id IS NULL) OR (producto_id IS NULL AND servicio_id IS NOT NULL)', name='ck_detalle_venta_item'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_ventas_id'), 'detalle_ventas', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura'),
    sa.UniqueConstraint('venta_id')
    )
    op.create_index(op.f('ix_facturas_cliente_id'), 'facturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('webhook_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_provider_transaction_id'), 'payments', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_venta_id'), 'payments', ['venta_id'], unique=False)
    op.create_table('detalle_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('(producto_id IS NOT NULL AND servicio_id IS NULL) OR (producto_id IS NULL AND servicio_id IS NOT NULL)', name='ck_detalle_factura_item'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_facturas_id'), 'detalle_facturas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_facturas_id'), table_name='detalle_facturas')
    op.drop_table('detalle_facturas')
    op.drop_index(op.f('ix_payments_venta_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_detalle_ventas_id'), table_name='detalle_ventas')
    op.drop_table('detalle_ventas')
    op.drop_index(op.f('ix_ventas_usuario_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_cliente_id'), table_name='ventas')
    op.drop_table('ventas')
    # ### end Alembic commands ###
